config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new'
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: 'pokemons#index'
  resources :pokemons, only: [:new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord

  belongs_to :user
  belongs_to :type_1, class_name: 'Type', optional: true
  belongs_to :type_2, class_name: 'Type', optional: true
  belongs_to :quality, optional: true
  belongs_to :move_1_type, class_name: 'Type', optional: true
  belongs_to :move_2_type, class_name: 'Type', optional: true
  belongs_to :move_3_type, class_name: 'Type', optional: true
  belongs_to :move_4_type, class_name: 'Type', optional: true

end

app/models/quality.rb
class Quality < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_login
    unless login?
      redirect_to login_url
    end
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  before_action :require_user_login
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @pokemons = Pokemon.where(user_id: current_user.id).order(number: :asc)
  end

  def new
    @pokemon = Pokemon.new
    @types = Type.order(id: :asc)
    @qualities = Quality.order(id: :asc)
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @types = Type.order(id: :asc)
    @qualities = Quality.order(id: :asc)
    @pokemon.user_id = current_user.id
    if @pokemon.save
      flash[:success] = '登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def edit
    @types = Type.order(id: :asc)
    @qualities = Quality.order(id: :asc)
  end

  def update
    @types = Type.order(id: :asc)
    @qualities = Quality.order(id: :asc)
    if @pokemon.update(pokemon_params)
      flash[:success] = '更新しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @pokemon.destroy
    flash[:success] = "削除しました"
    redirect_to root_url
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:number, :name, :type_1_id, :type_2_id, :ability, :quality_id, :move_1_name, :move_1_type_id, :move_2_name, :move_2_type_id, :move_3_name, :move_3_type_id, :move_4_name, :move_4_type_id)
  end

  def ensure_correct_user
    @pokemon = Pokemon.find(params[:id])
    @user = User.find(@pokemon.user_id)
    if @user.id != current_user.id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user_login, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = '更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "削除しました"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if @current_user
      return @current_user
    else
      @current_user = User.find_by(id: session[:user_id])
      return @current_user
    end
  end

  def login?
    if current_user
      return true
    else
      return false
    end
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message.html_safe %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-5">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Rescue Team DX Club</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if login? %>
          <li class="nav-item"><%= link_to current_user.name, user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rescue Team DX Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pokemons/edit.html.erb
<div class="text-center">
  <h1><%= @pokemon.name %></h1>
</div>
<div class="row my-5">
  <div class="offset-sm-3 col-sm-6">
    <%= form_with(model: @pokemon, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :number, '図鑑番号' %>
        <%= f.number_field :number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :type_1, 'タイプ１' %>
        <%= f.collection_select :type_1_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :type_1, 'タイプ２' %>
        <%= f.collection_select :type_2_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :ability, '特性' %>
        <%= f.text_field :ability, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :quality, 'すごわざ' %>
        <%= f.collection_select :quality_id, @qualities, :id, :name, {value: @pokemon.quality}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_1_name, 'わざ１' %>
        <%= f.text_field :move_1_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_1_type, 'わざ１のタイプ' %>
        <%= f.collection_select :move_1_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_2_name, 'わざ２' %>
        <%= f.text_field :move_2_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_2_type, 'わざ２のタイプ' %>
        <%= f.collection_select :move_2_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_3_name, 'わざ３' %>
        <%= f.text_field :move_3_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_3_type, 'わざ３のタイプ' %>
        <%= f.collection_select :move_3_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_4_name, 'わざ４' %>
        <%= f.text_field :move_4_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_4_type, 'わざ４のタイプ' %>
        <%= f.collection_select :move_4_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <%= f.submit '登録する', class: 'btn btn-primary btn-block mt-5' %>
    <% end %>
  </div>
</div>

app/views/pokemons/index.html.erb
<div class="text-center mb-5">
  <h1>ポケモン一覧</h1>
  <p class="mt-5"><%= link_to '新規登録', "/pokemons/new", class: 'btn btn-lg btn-primary' %></p>
  <div class="row mt-5">
    <% @pokemons.each do |pokemon| %>
      <div style="height: 300px" class="offset-xl-0 col-xl-6 offset-lg-2 col-lg-8 offset-md-1 col-md-10 offset- border pt-5 pb-3">
        <p>
          <span class="mr-3 font-weight-bold h4">No.<%= pokemon.number %></span>
          <%= link_to pokemon.name, edit_pokemon_path(pokemon), class: 'font-weight-bold h4 mr-3' %>
          <% if pokemon.type_1 %>
            <img class="rounded" src=<%= "/types/#{pokemon.type_1.image}" %> alt="Type" width="40px" height="40px">
          <% end %>
          <% if pokemon.type_2 %>
            <img class="rounded" src=<%= "/types/#{pokemon.type_2.image}" %> alt="Type" width="40px" height="40px">
          <% end %>
        </p>
        <table class="table table-borderless">
          <tr>
            <th style="width: 50%"><%= pokemon.ability %></th>
            <th style="width: 50%"><%= pokemon.quality.name %></th>
          </tr>
          <tr style="color: whitesmoke; text-shadow: 1px  1px 0px #000, -1px  1px 0px #000, 1px -1px 0px #000, -1px -1px 0px #000, 1px  0px 1px #000, 0px  1px 1px #000, -1px  0px 1px #000, 0px -1px 1px #000">
            <% if pokemon.move_1_type %>
              <td style="border: 1px solid black" bgcolor="<%= Type.find_by(id: pokemon.move_1_type_id).color %>"><span class="font-weight-bold"><%= pokemon.move_1_name %></span></td>
            <% end %>
            <% if pokemon.move_2_type %>
              <td style="border: 1px solid black" bgcolor="<%= Type.find_by(id: pokemon.move_2_type_id).color %>"><span class="font-weight-bold"><%= pokemon.move_2_name %></span></td>
            <% end %>
          </tr>
          <tr style="color: whitesmoke; text-shadow: 1px  1px 0px #000, -1px  1px 0px #000, 1px -1px 0px #000, -1px -1px 0px #000, 1px  0px 1px #000, 0px  1px 1px #000, -1px  0px 1px #000, 0px -1px 1px #000">
            <% if pokemon.move_3_type %>
              <td style="border: 1px solid black" bgcolor="<%= Type.find_by(id: pokemon.move_3_type_id).color %>"><span class="font-weight-bold"><%= pokemon.move_3_name %></span></td>
            <% end %>
            <% if pokemon.move_4_type %>
              <td style="border: 1px solid black" bgcolor="<%= Type.find_by(id: pokemon.move_4_type_id).color %>"><span class="font-weight-bold"><%= pokemon.move_4_name %></span></td>
            <% end %>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/new.html.erb
<div class="text-center">
  <h1>ポケモン新規登録</h1>
</div>
<div class="row my-5">
  <div class="offset-sm-3 col-sm-6">
    <%= form_with(model: @pokemon, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :number, '図鑑番号' %>
        <%= f.number_field :number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :type_1, 'タイプ１' %>
        <%= f.collection_select :type_1_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :type_2, 'タイプ２' %>
        <%= f.collection_select :type_2_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :ability, '特性' %>
        <%= f.text_field :ability, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :quality, 'すごわざ' %>
        <%= f.collection_select :quality_id, @qualities, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_1_name, 'わざ１' %>
        <%= f.text_field :move_1_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_1_type, 'わざ１のタイプ' %>
        <%= f.collection_select :move_1_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_2_name, 'わざ２' %>
        <%= f.text_field :move_2_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_2_type, 'わざ２のタイプ' %>
        <%= f.collection_select :move_2_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_3_name, 'わざ３' %>
        <%= f.text_field :move_3_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_3_type, 'わざ３のタイプ' %>
        <%= f.collection_select :move_3_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_4_name, 'わざ４' %>
        <%= f.text_field :move_4_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :move_4_type, 'わざ４のタイプ' %>
        <%= f.collection_select :move_4_type_id, @types, :id, :name, {prompt: "選択してください"}, class: 'form-control' %>
      </div>
      <%= f.submit '登録する', class: 'btn btn-primary btn-block mt-5' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>登録情報編集</h1>
</div>
<div class="row my-5">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, value: @user.name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, value: @user.email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（再確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit '更新する', class: 'btn btn-primary btn-block mt-5' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>
<div class="row my-5">
  <div class="offset-sm-3 col-sm-6">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（再確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit '登録する', class: 'btn btn-primary btn-block mt-5' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center mb-5">
  <h1><%= @user.name %></h1>
  <div class="row mt-5">
    <table class="offset-lg-3 col-lg-6 table table-bordered">
      <tr>
        <td>お名前</td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @user.email %></td>
      </tr>
    </table>
  </div>
  <p class="mt-5"><%= link_to '登録情報編集', edit_user_path(@user), class: 'btn btn-lg btn-primary' %></p>
  <p class="mt-5"><%= link_to 'アカウントを削除する', user_path(@user), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'text-danger' %></p>
</div>